---

apache_default_port: "8081"
apache_default_group: "www-data"
apache_default_user: "root"

dns_nameservers:
- 8.8.8.8
- 8.8.4.4

keepalived_shared_iface: "eth1"
keepalived_shared_vip: "192.168.56.70"

logstash_host: "sa02"

mysql_root_password: "Password123"

nginx_default_port: "80"

tomcat_port_default: "8080"
tomcat_sample_app_name: "mysql-sample"
tomcat_sample_app_mysql_user: "tomcat-user"
tomcat_sample_app_mysql_password: "Password123"
tomcat_sample_app_mysql_database: "tomcat_sample"

htpasswd_file_location: "/etc/htpasswd"
htpasswd_dict:
  user01:
    name: nagiosadmin
    password: nagiosadmin
  user02:
    name: kibanaadmin
    password: kibanaadmin
  user03:
    name: admin
    password: admin
  user04:
    name: jack
    password: Password123
  user05:
    name: jill
    password: Password123
  user06:
    name: lucas
    password: Password1234
  user07:
    name: caroline
    password: Password1234

nagios_host: 192.168.56.80
NagiosClients:
  - info:
    NagiosClient_Name: lb01
    NagiosClient_Alias: load-balancer-01
    NagiosClient_IP: 192.168.56.71
  - info:
    NagiosClient_Name: lb02
    NagiosClient_Alias: load-balancer-02
    NagiosClient_IP: 192.168.56.72
  - info:
    NagiosClient_Name: web01
    NagiosClient_Alias: web-server-01
    NagiosClient_IP: 192.168.56.73
  - info:
    NagiosClient_Name: web02
    NagiosClient_Alias: web-server-02
    NagiosClient_IP: 192.168.56.74
  - info:
    NagiosClient_Name: db01
    NagiosClient_Alias: database-server-01
    NagiosClient_IP: 192.168.56.76
  - info:
    NagiosClient_Name: sa01
    NagiosClient_Alias: service-assurance-01
    NagiosClient_IP: 192.168.56.80
  - info:
    NagiosClient_Name: sa02
    NagiosClient_Alias: service-assurance-02
    NagiosClient_IP: 192.168.56.81

haproxy_line_item:
  - 'listen stats :8181'
  - ' mode http'
  - ' stats enable'
  - ' stats realm Haproxy\ Statistics'
  - ' stats uri /'
  - ' stats auth haproxy:haproxy'
  - ' '
  - 'listen web-servers-apache'
  - ' bind {{ keepalived_shared_vip }}:8081'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:8081 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:8081 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:8081 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen web-servers-nginx'
  - ' bind {{ keepalived_shared_vip }}:80'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:80 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:80 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:80 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen web-servers-tomcat'
  - ' bind {{ keepalived_shared_vip }}:8080'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:8080 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:8080 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:8080 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen db-servers-mysql'
  - ' bind {{ keepalived_shared_vip }}:3306'
  - ' balance roundrobin'
  - ' mode tcp'
  - ' server db01 192.168.56.76:3306 check inter 2000 rise 2 fall 5'
  - ' server db02 192.168.56.77:3306 check inter 2000 rise 2 fall 5'
  - ' server db03 192.168.56.78:3306 check inter 2000 rise 2 fall 5'
