---

- name: Fetch the generated public certificate
  fetch:
    src: "/etc/pki/tls/certs/logstash-forwarder.crt"
    dest: "/tmp/logstash-forwarder.crt"
    flat: yes
  run_once: true
  delegate_to: "{{ logstash_host }}"

- name: Create PKI directory structure
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0644
  with_items:
    - /etc/pki
    - /etc/pki/tls
    - /etc/pki/tls/certs

- name: Copy logstash-forwarder certificate
  copy:
    src: "/tmp/logstash-forwarder.crt"
    dest: "/etc/pki/tls/certs/logstash-forwarder.crt"
    owner: root
    group: root
    mode: 0644

- name: Add apt key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: add Debian based repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb https://packages.elastic.co/beats/apt stable main'

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - filebeat
    - topbeat

- name: Configure filebeat
  template:
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
    backup: yes
  notify: restart filebeat

- name: Configure topbeat
  template:
    src: topbeat.j2
    dest: /etc/topbeat/topbeat.yml
    mode: 0644
    backup: yes
  notify: restart topbeat

- name: Start the service and enable on startup on Debian based systems
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - filebeat
    - topbeat
