---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant

  tasks:
  - name: Generate SSH key
    user: name=vagrant generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
