---

keepalived_shared_iface: "eth1"
keepalived_shared_vip: "192.168.56.70"

apache_default_port: "8081"
apache_default_group: "www-data"
apache_default_user: "root"

htpasswd_file_location: "/etc/htpasswd"
htpasswd_accounts:
  - name: User Names and Passwords
    htpasswd_credentials:
      - { name: nagiosadmin, password: nagiosadmin }
      - { name: admin, password: admin }
      - { name: jack, password: Password123 }
      - { name: jill, password: Password123 }
      - { name: lucas, password: Password1234 }

nginx_default_port: "80"

mysql_root_password: "Password123"

tomcat_port_default: "8080"
tomcat_sample_app_name: "mysql-sample"
tomcat_sample_app_mysql_user: "tomcat-user"
tomcat_sample_app_mysql_password: "Password123"
tomcat_sample_app_mysql_database: "tomcat_sample"

haproxy_line_item:
  - 'listen stats :8181'
  - ' mode http'
  - ' stats enable'
  - ' stats realm Haproxy\ Statistics'
  - ' stats uri /'
  - ' stats auth haproxy:haproxy'
  - ' '
  - 'listen web-servers-apache'
  - ' bind {{ keepalived_shared_vip }}:8081'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:8081 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:8081 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:8081 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen web-servers-nginx'
  - ' bind {{ keepalived_shared_vip }}:80'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:80 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:80 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:80 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen web-servers-tomcat'
  - ' bind {{ keepalived_shared_vip }}:8080'
  - ' balance roundrobin'
  - ' mode http'
  - ' option forwardfor'
  - ' option httplog'
  - ' option http-server-close'
  - ' server web01 192.168.56.73:8080 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:8080 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:8080 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen db-servers-mysql'
  - ' bind {{ keepalived_shared_vip }}:3306'
  - ' balance  roundrobin'
  - ' mode  tcp'
  - ' server db01 192.168.56.76:3306 check inter 2000 rise 2 fall 5'
  - ' server db02 192.168.56.77:3306 check inter 2000 rise 2 fall 5'
  - ' server db03 192.168.56.78:3306 check inter 2000 rise 2 fall 5'
