---

haproxy_line_item:
  - 'listen web-servers-nginx'
  - ' bind 192.168.56.70:80'
  - ' balance  roundrobin'
  - ' mode  http'
  - ' server web01 192.168.56.73:80 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:80 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:80 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen web-servers-tomcat'
  - ' bind 192.168.56.70:8080'
  - ' balance  roundrobin'
  - ' mode  http'
  - ' server web01 192.168.56.73:80 check inter 2000 rise 2 fall 5'
  - ' server web02 192.168.56.74:80 check inter 2000 rise 2 fall 5'
  - ' server web03 192.168.56.75:80 check inter 2000 rise 2 fall 5'
  - ' '
  - 'listen db-servers-mysql'
  - ' bind 192.168.56.70:3306'
  - ' balance  roundrobin'
  - ' mode  tcp'
  - ' server db01 192.168.56.76:3306 check inter 2000 rise 2 fall 5'
  - ' server db02 192.168.56.77:3306 check inter 2000 rise 2 fall 5'
  - ' server db03 192.168.56.78:3306 check inter 2000 rise 2 fall 5'
