---

#- name: Update cache if greater than 3600 seconds (1 hour)
#  apt:
#    update_cache: yes
#    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nagios-plugins
    - nagios-nrpe-server

- name: Copy template file
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    mode: 0644
    backup: yes
  notify: restart nagios-nrpe-server

- name: Start the service and enable on startup
  service:
    name: nagios-nrpe-server
    enabled: yes
    state: started
