---

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart nagios
  service:
    name: nagios
    state: restarted

- name: reload nagios
  service:
    name: nagios
    state: reloaded
