---

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart carbon
  service:
    name: carbon-cache
    state: restarted

- name: restart collectd
  service:
    name: collectd
    state: restarted
