---

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Copy html index
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0644
    backup: yes

- name: Set default site configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default  # symlink to /etc/nginx/sites-enabled/default
    mode: 0644
    backup: yes
  notify: reload nginx

- name: enable service on startup
  service:
    name: nginx
    enabled: yes
    state: started
