- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd
    - collectd-utils

- name: Configure collectd
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    mode: 0644
    backup: yes
  notify: restart collectd

- name: Start the service and enable on startup
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - collectd
