---

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:  
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Delete anonymous MySQL server user
  mysql_user: 
    user: ""
    host: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_nodename }}"
    - localhost

- name: Remove the MySQL test database
  mysql_db:
    db: test
    state: absent

- name: Update MySQL Root Password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
    - "127.0.0.1"
    - "::1"
    - "{{ ansible_hostname }}"
    - "{{ ansible_nodename }}"
    - "{{ mysql_allow_from }}"
    - localhost

- name: Copy MySQL client config
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644

- name: Configure mysql bindings
  lineinfile:
    dest: /etc/mysql/my.cnf
    line: "bind-address            = {{ facter_ipaddress_eth1 }}"
    regexp: "^bind-address"
  notify: restart mysql

- name: Start service and enable on startup
  service:
    name: mysql
    enabled: yes
    state: started
