---

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - keepalived

- name: copy conf file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  notify: restart keepalived

- name: enable service on startup
  service: 
    name: keepalived 
    enabled: yes

- name: start the service
  service: 
    name: keepalived 
    state: started