---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - name: Generate SSH key for Vagrant
    user:
      name: vagrant
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Generate SSH key for Root
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
