---
- hosts: lb-servers
  sudo: yes
  gather_facts: yes

  tasks:
    - name: install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - haproxy
        - keepalived
