---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: setup SSH trust amongst instances
    authorized_key: 
      user: vagrant
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
      state: present

  - name: Add ssh public key to vagrant account
    authorized_key: 
      user: vagrant
      key: "{{ item }}"
      state: present 
    with_file:
      - myPublicKey

  - name: Add ssh public key to root acount
    authorized_key: 
      user: root
      key: "{{ item }}"
      state: present
    with_file:
      - myPublicKey